name: Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Rsync update
      env:
        deploy_key: ${{secrets.deploy_key}}
        known_hosts: ${{secrets.known_hosts}}
      run: |
        mkdir -p ${HOME}/.ssh
        printf "%s\n" "$known_hosts" > ${HOME}/.ssh/known_hosts
        printf "%s\n" "$deploy_key" > ${HOME}/.ssh/id_ed25519
        chmod 600 ${HOME}/.ssh/id_ed25519
        rsync -a ./ github@remi-lemoust.com:/home/github/Portfolio